"""initial

Revision ID: 3713cb3a645a
Revises: 53d5cc029f54
Create Date: 2025-11-13 11:05:03.027281+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '3713cb3a645a'
down_revision = '53d5cc029f54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

