"""initial

Revision ID: 44b3e6b8710d
Revises: 20250113_000001
Create Date: 2025-11-13 11:03:37.202667+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '44b3e6b8710d'
down_revision = '20250113_000001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_items_reported_by_user_id'), 'items', ['reported_by_user_id'], unique=False)
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.create_index(op.f('ix_matches_finder_id'), 'matches', ['finder_id'], unique=False)
    op.create_index(op.f('ix_matches_loser_id'), 'matches', ['loser_id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_matches_loser_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_finder_id'), table_name='matches')
    op.create_index(op.f('ix_matches_status'), 'matches', ['match_status'], unique=False)
    op.drop_index(op.f('ix_items_reported_by_user_id'), table_name='items')
    # ### end Alembic commands ###

