"""initial

Revision ID: 53d5cc029f54
Revises: 44b3e6b8710d
Create Date: 2025-11-13 11:04:18.446115+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '53d5cc029f54'
down_revision = '44b3e6b8710d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

